title: CSE 110 Lab1

name: Chi Zhang
email: chz043@ucsd.edu

description: This is the webpage for CSE 110 Lab1

twitter_username: chizhang0810
github_username:  chizhang9135
linkedin_username: chizhang0810

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
